apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: craftsman-app-deployment
  name: craftsman-app-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: craftsman-app-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: craftsman-app-deployment
    spec:
      containers:
      - image: docker.io/matrima/craftsmanapp:v1
        imagePullPolicy: IfNotPresent
        name: craftsmanapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CARPENTER-API-IP
          value: "carpenter-api-balancer"
        - name: CARPENTER-API-PORT
          value: "8080"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: craftsman-app-deployment
  name: craftsman-app-deployment
  namespace: default
spec:
  clusterIP: 10.0.5.156
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30228
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: craftsman-app-deployment
  sessionAffinity: None
  type: LoadBalancer