apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: carpenter-api-deployment
  name: carpenter-api-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: carpenterapi-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carpenterapi-deployment
    spec:      
      containers:
      - image: docker.io/matrima/carpenterapi:v6
        imagePullPolicy: IfNotPresent
        name: carpenterapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env: 
        - name: CARPENTER-MONGODB-IP
          value: "34.91.119.227"
        - name: CARPENTER-MONGODB-PORT
          value: "8080"        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: carpenter-api-deployment
  name: carpenter-api-balancer
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: carpenterapi-deployment
  sessionAffinity: None
  type: LoadBalancer