apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: craftsman-api-deployment
  name: craftsman-api-deployment
  namespace: itonk-ap1-gr21
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: craftsman-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: craftsman-deployment
    spec:      
      containers:
      - image: docker.io/matrima/craftsmanapi:v4
        imagePullPolicy: IfNotPresent
        name: craftsmanapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env: 
        - name: CRAFTSMAN-MONGODB-IP
          value: "10.11.252.14"
        - name: CRAFTSMAN-MONGODB-PORT
          value: "8080"        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: craftsman-api-deployment
  name: craftsman-api-balancer
  namespace: itonk-ap1-gr21
spec:
  clusterIP: 10.11.245.65
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: craftsman-deployment
  sessionAffinity: None
  type: ClusterIP