# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-02T12:39:29Z"
  generation: 1
  labels:
    app: carpenter-mongodb
  name: carpenter-mongodb
  namespace: default
  resourceVersion: "13099"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/carpenter-mongodb
  uid: dbbe39f1-5c82-11ea-a88a-42010aa40022
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: carpenter-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carpenter-mongodb
    spec:
      volumes:
      - name: mongodb-data
        gcePersistentDisk:
          pdName: mongodb
          fsType: ext4 
      containers:
      - image: docker.io/library/mongo:latest      
        imagePullPolicy: Always
        name: mongo
        volumeMounts: 
        - name: mongodb-data
          mountPath: /data/db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-02T12:39:42Z"
    lastUpdateTime: "2020-03-02T12:39:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-02T12:39:29Z"
    lastUpdateTime: "2020-03-02T12:39:42Z"
    message: ReplicaSet "carpenter-mongodb-8b7c6dc79" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
