apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: carpenter-mongodb
  name: carpenter-mongodb
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: carpenter-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carpenter-mongodb
    spec:
      volumes:
      - name: mongodb-data
        gcePersistentDisk:
          pdName: mongodb
          fsType: ext4 
      containers:
      - image: docker.io/library/mongo:latest      
        imagePullPolicy: Always
        name: mongo
        volumeMounts: 
        - name: mongodb-data
          mountPath: /data/db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: carpenter-mongodb
  name: carpenter-mongodb-balancer
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: carpenter-mongodb
  sessionAffinity: None
  type: LoadBalancer
